### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by Be-ing** [clarissalimab/ux#6]
Hi @clarissalimab, I watched your [presentation at LibrePlanet 2021](https://framatube.org/videos/watch/02151d79-d422-4012-a547-e01c9e54c7f7) and I love the idea of this repository. It looks like you've written the documents with the intention of them being copied verbatim or modified into other projects' repositories. It would help to explicitly state the licensing of these documents. I suggest Creative Commons Attribution Share Alike.

**Comment by clarissalimab** [comment]
Hi @Be-ing! Thanks for your interest. You are right, I forgot to add the license. I will do it tomorrow :)

**Comment by Be-ing** [comment]
Thanks!
